### ISSUE TITLE
Example app?

### ISSUE THREAD

**Issue by holgersindbaek** [n0xgg04/expo-applovin-ads#2]
I'm about to implement applovin in my expo app so I could really use something like this. I can't get the library to work with my android app though.

Could you create an example app or elaborate on how to implement the library?

**Comment by Kami-prog** [comment]
download
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by n0xgg04** [comment]
yes ofc, i will add it soon

**Comment by holgersindbaek** [comment]
> yes ofc, i will add it soon

I look forward to it. Thanks! Keep up the good work!

**Comment by n0xgg04** [comment]
i added example app and READ ME. Check it !

**Comment by holgersindbaek** [comment]
Awesome! I'll look into it first thing next week.
